//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFTTestBackend.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public int Client_Type_Id { get; set; }
    
        public virtual Client_Type Client_Type { get; set; }
    }
}
